### ISSUE TITLE
[BUG] Joining messages not relaying on 1.20.6

### ISSUE THREAD

**Issue by FuzzyL16** [hypherionmc/sdlink#115]
When joining the server the message doesn't get relayed to discord, leaving messages does relay thought.

**Comment by hypherionmc** [comment]
Unless you are using the version from our snapshots, 1.20.6 is not supported, so it won't work

**Comment by FuzzyL16** [comment]
Would you know when we might expect support for version 1.20.6?

**Comment by hypherionmc** [comment]
We aren't doing any official 1.20.6 releases, for a variety of reasons, but the good news is, there are 1.20.6 versions that are available for use.

Since it's server side, you can use it without the players having it.

CraterLib - [1.20.6](https://nightbloom.cc/project/craterlib?mc=1.20.6)
SDLink - [1.20.6](https://nightbloom.cc/project/sdlink?mc=1.20.6)

**Comment by FuzzyL16** [comment]
That's good to know although I won't be able to use it on Aternos

**Comment by hypherionmc** [comment]
1.21 was released today. Going to close this for now, since we never officially supported 1.20.6
