### ISSUE TITLE
[Bug] User avatars depreciate when more users log on

### ISSUE THREAD

**Issue by AllOutJay** [hypherionmc/sdlink#12]
Minecraft version:
Minecraft 1.19

Mod Version:
[Fabric/Quilt 1.19.x] Simple Discord Link - 1.3.0

Description of the issue:
The bot appears to break when more players begin to come online (like 5). The avatars for each user temporarily display as a blank Discord avatar, but anything server oriented still shows as the bot's server avatar.

[Image of the issue](https://imgur.com/HaiVRXe)

[simple-discord-bot.txt](https://github.com/hypherionmc/sdlink/files/8936421/simple-discord-bot.txt)
[Discord permissions](https://user-images.githubusercontent.com/80604256/174500921-7cae6854-4380-446b-a777-d56efc0548d7.png)

**Comment by hypherionmc** [comment]
Hi. Thanks for your report and sorry for not responding earlier. Been working all weekend.

That is a strange one. It could come down to one of two issues:

A) Discord glitching because of how much the avatar changes, or, having some sort of undocumented rate limit on that

B) A cravatar server issue or rate limit I don't know about.

B being the easier one to fix, by simply caching the images, and not having to make so many calls to their api.

I'll try to replicate this issue on my side, if I can get a couple of people to assist with testing

**Comment by hypherionmc** [comment]
I switched to a different API that caches the images themselves, so hopefully that fixes this error. I don't have enough people to help test this myself

**Comment by hypherionmc** [comment]
Release has been made with this "fix" implemented. Keeping this open incase the issue still persists

**Comment by AllOutJay** [comment]
Will test it this weekend to verify if this would have fixed it.

**Comment by AllOutJay** [comment]
@hypherionmc I believe your fix has solved the problem.
