### ISSUE TITLE
[Feature] Support offline mode whitelist

### ISSUE THREAD

**Issue by Azarattum** [hypherionmc/sdlink#18]
I'm using [EasyAuth](https://github.com/NikitaCartes/EasyAuth) to allow both Mojang authenticated and non-authenticated users to join my server. I've encountered a problem that when adding a player to whitelist with `sdlink` it assumes the online UUID. So, the whitelist becomes broken for offline-mode players. Could you maybe add a way to specify offline mode while whitelisting?

**Comment by Ecorous** [comment]
Uh, no. I highly doubt that hypher will support pirating Minecraft. Get your friends or whoever makes you need offline mode to buy the game

**Comment by hypherionmc** [comment]
It's not really so much about "Supporting Piracy", as there are legit reasons to run servers in offline mode, but the issue here is that the bot uses the built in minecraft whitelist system, which always expects players UUID to be the ONLINE one.

This will require implementing another whitelist solution, which just handles offline whitelisting. Not impossible, as I've made a mod before that does that.

Or, we need to just drop using the built in system completely, and have the bot fully control the whitelisting.

**Comment by Azarattum** [comment]
As far as I know, if you just put an offline UUID in the `whitelist.json` it should work without any mods required. That's what I'm doing now. Players ask me to add them, then I manually edit the UUID entry. 

The question is, how the bot can obtain the said offline UUID (since I've been getting it from logs)?

If that is possible I would very like to see some kind of `whitelist <player name> offline` discord command that would edit `whitelist.json` properly.

**Comment by Azarattum** [comment]
Also, @hypherionmc, could you link the mod you were talking about? What does it do exactly?

**Comment by hypherionmc** [comment]
The mod is on my curse page, but hasn't been updated since 1.12.2, cause I messed something up in the port and never really bothered to check again, because the mod wasn't used that much.

As for retrieving the offline UUID, there was an API I used for said mod that retrieved it, but I'll look into doing it without having to use an API, cause API's are unreliable at best lol

**Comment by Azarattum** [comment]
That should be possible in theory. Singleplayer worlds do this somehow while keeping it consistent (correct me if I'm wrong). I guess there's some kind of a hash function from a username is involved.

**Comment by Azarattum** [comment]
@hypherionmc I found a way to get offline UUID from a username:
```java
UUID.nameUUIDFromBytes(("OfflinePlayer:" + offlineName).getBytes(StandardCharsets.UTF_8));
```
where `UUID` is from `import java.util.UUID;`.

Source: https://github.com/paul-eff/MinecraftOfflineOnlineConverter/blob/main/src/main/java/me/paulferlitz/UUIDHandler.java

**Comment by hypherionmc** [comment]
Thank you. I'll work this into the next update

**Comment by hypherionmc** [comment]
Just finished testing/adding this. Seems like it's working

**Comment by hypherionmc** [comment]
Version 2.0 now contains this feature
