### ISSUE TITLE
Receiving duplicate chat messages in discord after updating to the latest version

### ISSUE THREAD

**Issue by ChristopherHaws** [hypherionmc/sdlink#35]
After updating to the latest version, I am getting many duplicates of messages in discord. Here is an example:
![image](https://user-images.githubusercontent.com/5934505/211187088-ba10e02b-7118-4483-81da-5683ca0da60d.png)

**Comment by hypherionmc** [comment]
I've gotten a similar report on Discord. Seems to be linked to the experimental formatting option. It should be fixed if you disable formatting in the config

**Comment by hypherionmc** [comment]
Alright, so this issue should be fixed with Version 2.2. Before pushing a release, I would love if people can help me test.

This release doesn't contain a lot of new features, but we made some changes to try and improve performance, and also clear out some of the older errors.

Most noticeable change is that you can now format the "command executed" messages, as well as choose if you want the full command executed relayed or not.

This also brings in some additional error handling on the console channel

https://ci.firstdarkdev.xyz/job/Simple%20Discord%20Link/job/Forge-Fabric-Quilt/

**Comment by hypherionmc** [comment]
Fixed in v2.2.0
