### ISSUE TITLE
Animated Discord Status & afk command

### ISSUE THREAD

**Issue by GiantessElsie** [hypherionmc/sdlink#44]
I have a request or 2 my request like under your bot's name is it the bot's status like watching example or playing example so what if u could make it that your status can change ever 5 seconds to Watching example 1 then watching example 2 then example 3

And last if u can make it if u type /afk it shows u are afk on minecraft and on your discord server

**Comment by KuryKat** [comment]
"Animated" wouldn't really be the correct name, but yes, it is TO-DO for v4 to have the status select randomly one from a list of status.

I would also say (and recommend) to create one Issue per suggestion, so that this way we can manage them better. For example, if you suggest 10 things (just an exaggeration) in one singular issue, and then we reject ONE of them, the issue needs to be closed, and the other ideas might not even be considered, depending on the situation they might be but they won't be linked to the Issue that initially suggested them.

**Comment by KuryKat** [comment]
Also, the "AFK Command" idea is to be something like [this](https://dev.bukkit.org/projects/afk)?

**Comment by hypherionmc** [comment]
Multiple discord statuses implemented in 3.2.1
