### ISSUE TITLE
Goodbye message when server does not response/appears offline

### ISSUE THREAD

**Issue by jankornfeld** [hypherionmc/sdlink#54]
Hi there,
Firstly nice mod.

Secondly it would be nice if the bot would say goodbye or something when the minecraft server is not responding anymore.
I currently got a little problem, that the server at some point appears to be offline and then the bot instead of saying "Server not responding" or "Server might be offline. Please check", the bot goes off.

Would be a nice to have feature.
BR
Jan

**Comment by hypherionmc** [comment]
Hi. 

Thanks for the feedback. That one might be a little hard or impossible to do. 

The bot, or any mod in general requires constant updates from the server. If the server is not responding anymore, it effectively means the mods don't continue to run anymore. That's why the bot turns off without saying anything, as there is nothing telling it to stay alive anymore and discord disconnects it for not responding. 


Depending on how the server stops responding, depends on how this could work. If the server just stays running, but does nothing (not responding basically), the behavior you mentioned will always be the expected behavior.

If the server actually crashes, but stays running, there might be a way to hook into that and have the bot deliver one last message before the server dies. If you can/want, you can share your server logs from when these events occur, and I can try to figure out what happens before then, and see if it's possible to implement such a feature

**Comment by jankornfeld** [comment]
Ah... stupid me. You created the mod and not the discord bot.

The server appears to be running just fin but the whole machine seems to be of the internet. So there is no server crash or so to help you out.

I think you can close this issue then if you want.

**Comment by hypherionmc** [comment]
Well the discord bot is technically the mod lol, but if the machine itself goes offline (loses internet connection), then the bot can't communicate with discord and will go offline as well.

However, when the machine does regain internet connection, the bot is supposed to come back online. If it doesn't do that, then it is a bug
