### ISSUE TITLE
When Quark's item sharing feature is used, you will be kick from the server with simple discord link installed. 

### ISSUE THREAD

**Issue by thelegitdolt** [hypherionmc/sdlink#61]
Link of quark https://www.curseforge.com/minecraft/mc-mods/quark

Quark mod has a feature that allows you to share an item in the chat.
<img width="935" alt="Screen Shot 2023-06-14 at 23 49 50" src="https://github.com/hypherionmc/sdlink/assets/50085439/40d4fc40-b854-404c-bf72-890374b13c96">

However, when this feature is used with simple discord link installed, the player who shared this item will be kicked from the server. We are currently using Quark 405 and Simple Discord Link 1.19.1-2.2.2.

This is the log output when the player is disconnected from the server: https://gist.github.com/thelegitdolt/8b74093e650b177a13bff378a21d89c8. I am unsure where to get any additional information about the crash, please tell me if you need anything.

**Comment by hypherionmc** [comment]
Hey.

So I'm not 100% sure this issue is caused by SDLink. The only mention of an error in the log you shared, is from quark itself. `Error at reading message vazkii.quark.base.network.message.ShareItemMessage@2fc0c8bc`. 

Did you test this without sdlink installed to see if it still does this? SDLink shouldn't interact with items and blocks at all, since it only handles chat related stuff.

Will test this on my side as well to confirm

**Comment by thelegitdolt** [comment]
Thank you for the fast reply. It is possible that this happened on quark's end, as I updated quark at the same time as I installed the mod. I will also do testing without the mod installed.

**Comment by hypherionmc** [comment]
Thanks. Will let you know what the result was from my side as well

**Comment by thelegitdolt** [comment]
Deleted SDL, and the crash still persists. Probably a quark issue
