### ISSUE TITLE
Server crash on start up

### ISSUE THREAD

**Issue by Yamadaisme** [hypherionmc/sdlink#83]
![image](https://github.com/hypherionmc/sdlink/assets/92765169/39b391b8-3deb-4207-9cf4-202a315a25a8)
When I tried to start up the server with the forge mods and the required dependency. It crashed with no specific reason. 
I attached the error shown when I start up the server with the debug file here: https://mclo.gs/JGrwB54

**Comment by LazrProductions** [comment]
getting the same issue here

**Comment by hypherionmc** [comment]
This issue should've been fixed with the latest release of SDLink, which ironically, is another broken version. This issue has been fixed fully in the upcoming V3 release, which goes out as a beta soon.

For now, I think most Groovy Mod Loader mods are client side only, so you it should be safe to remove groovy from your server.

See here for more info: https://github.com/hypherionmc/sdlink/issues/67#issuecomment-1625652276

**Comment by hypherionmc** [comment]
This issue should be resolved with the last V2 and V3 beta releases. If not, please let me know
